version: '3'
volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: jetdj/yamdb:latest
    restart: always
    expose:
      - 8000
    volumes:
      - static_volume:/static/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
    ports:
      - 80:80
    depends_on:
      - web

